### ISSUE TITLE
how to fix it? onnxruntime error

### ISSUE THREAD

**Issue by wjstkqkdlz** [Nick088Official/FaceFusion-Online-Ports#25]
![image](https://github.com/user-attachments/assets/ed74d5f5-16d6-4169-8884-824f3579db72)
error like this in Lightning ai

**Comment by Nick088Official** [comment]
> ![image](https://private-user-images.githubusercontent.com/183503037/372463184-ed74d5f5-16d6-4169-8884-824f3579db72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODk5NjksIm5iZiI6MTcyNzc4OTY2OSwicGF0aCI6Ii8xODM1MDMwMzcvMzcyNDYzMTg0LWVkNzRkNWY1LTE2ZDYtNDE2OS04ODg0LTgyNGYzNTc5ZGI3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMzM0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjJiMTIyZmYyYzU3YWUyYzQ3ZjQ0NzI3YmY0Njk5N2Q1NjJlZjY5MDdlZTAwNWIxZGNhNDAyOGJjNDQwYWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8r7QT3wybXeJHn6Wn0fn1WNn2KMXpJaGDYPLmSf3hks) error like this in Lightning ai

Thank you for your report, I just pushed a fix for it, tested it and didn’t get that error anymore, it uses the GPU properly now, let me know!

**Comment by wjstkqkdlz** [comment]
![image](https://github.com/user-attachments/assets/2fa98a5e-275b-416e-9f93-06cd16b4520f)
It is still not working... :(

**Comment by Nick088Official** [comment]
> ![image](https://private-user-images.githubusercontent.com/183503037/372510897-2fa98a5e-275b-416e-9f93-06cd16b4520f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDUyMDQsIm5iZiI6MTcyNzgwNDkwNCwicGF0aCI6Ii8xODM1MDMwMzcvMzcyNTEwODk3LTJmYTk4YTVlLTI3NWItNDE2ZS05ZjkzLTA2Y2QxNmI0NTIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNzQ4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjQ0MDc5ZjhmMGRmODNkMDY0NDFkZmFiMzJhOWQ2NDY0NGNmMzQ4NjcwZjVhODIzZjA5YTI0ZmUxNGY1ZWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xrc4WjxkknwbeCy0UGqZHR73R5DKylTCkj8k2JkXm5w) I create a new studio from studio templates, but It is still not working... :(

Try to click 'open in studio' from https://lightning.ai/nick088/studios/facefusion-ui and be sure you are using the GPU, i just tried with images and has no error, be sure u are using the latest version

**Comment by Nick088Official** [comment]
I also tried it myself and a friend, both of us didn't have this issue

**Comment by wjstkqkdlz** [comment]
Thank you! It is working well!!

**Comment by wjstkqkdlz** [comment]
Umm.. There's another problem..
If you erase and reinstall the program, it works normally, but if you turn off the studio and use it again, an error occurs.
I can't even erase it and re-lay it every time, so I hope you check and correct it.

**Comment by Nick088Official** [comment]
> Umm.. There's another problem.. If you erase and reinstall the program, it works normally, but if you turn off the studio and use it again, an error occurs. I can't even erase it and re-lay it every time, so I hope you check and correct it.

What error? And if originally installed it on GPU, you turn off session and turn it on with CPU (Or other way around), you have to delete everything again and re install it as it has 2 different installations for those

**Comment by wjstkqkdlz** [comment]
I turn off session on GPU. But when I turn on later, I think the file is missing... 
I turned it on with gpu and I don't know why it disappears. Then, do I have to re-install the file every time I turn it on and on?

**Comment by Nick088Official** [comment]
> I turn off session on GPU. But when I turn on later, I think the file is missing... 

Which exact file is missing ?

> I turned it on with gpu and I don't know why it disappears. Then, do I have to re-install the file every time I turn it on and on?

Well lightning.ai storage is persistent so you don't have to,

unless you accidentally ran the "delete everything" cell which is not needed to run unless you:
- need to update facefusion 
 - change the accelerator (like you install on GPU, and to run it on CPU you have to delete everything and re install, and the other way around)

When you need to stop session, you can just click the ⬜ button to stop execution and then click the accelerator button and turn the studio to sleep

**Comment by wjstkqkdlz** [comment]
> > I turn off session on GPU. But when I turn on later, I think the file is missing...
> 
> Which exact file is missing ?
> file that can activate cuda
maybe onnxruntime or cudnn file?

> > I turned it on with gpu and I don't know why it disappears. Then, do I have to re-install the file every time I turn it on and on?
> 
> Well lightning.ai storage is persistent so you don't have to,
> 
> unless you accidentally ran the "delete everything" cell which is not needed to run unless you:
> 
> * need to update facefusion
> * change the accelerator (like you install on GPU, and to run it on CPU you have to delete everything and re install, and the other way around)
> 
> When you need to stop session, you can just click the ⬜ button to stop execution and then click the accelerator button and turn the studio to sleep
yeah I know that. But I think the file mentioned above will be deleted during the time I connect to gpu when I just start. Because I always turned off the session with gpu connected and turned it on automatically when I turned it on, but I see the phrase 'Failed to load library bonnxruntime_providers_cuda.so with error' appearing every time

**Comment by Nick088Official** [comment]
> > > I turn off session on GPU. But when I turn on later, I think the file is missing...
> > 
> > Which exact file is missing ?
> > file that can activate cuda
> maybe onnxruntime or cudnn file?
> 
> > > I turned it on with gpu and I don't know why it disappears. Then, do I have to re-install the file every time I turn it on and on?
> > 
> > Well lightning.ai storage is persistent so you don't have to,
> > 
> > unless you accidentally ran the "delete everything" cell which is not needed to run unless you:
> > 
> > * need to update facefusion
> > * change the accelerator (like you install on GPU, and to run it on CPU you have to delete everything and re install, and the other way around)
> > 
> > When you need to stop session, you can just click the ⬜ button to stop execution and then click the accelerator button and turn the studio to sleep
> yeah I know that. But I think the file mentioned above will be deleted during the time I connect to gpu when I just start. Because I always turned off the session with gpu connected and turned it on automatically when I turned it on, but I see the phrase 'Failed to load library bonnxruntime_providers_cuda.so with error' appearing every time

Huh?

**Comment by Nick088Official** [comment]
I looked into this issue, found some cases where it gives the error you said. For the meanwhile before running it, it will install and make sure the right cuda version is being used, which takes 1-2 mins but fixes it and runs perfectly on GPU. Later on I will see if I can find a faster way
